### ISSUE TITLE
Wrap functions that require non-pointer struct arguments

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/c2hs#117]
The Haskell FFI cannot handle pure struct arguments in foreign declarations, only struct pointers. Unfortunately, I deal with several libraries with functions that expect pure structs as arguments. As a simplified example:

```c
typedef struct {
    int x;
    int y;
} coord_t;

int coord_x(coord_t c) {
    return c.x;
}
```

There isn't any way for Haskell to call this directly. Instead, I'd first have to create another C file with a function that wraps `coord_x`:

```c
int wrap_coord_x(coord_t *c) {
    return coord_x(*c);
}
```

This gets to be pretty tedious and mechanical, which made me wonder if this process could be automated via build-tools. I know `c2hs` already generates `*.chs.h` files for CPP pragmas and other miscellanoues C code, so I wonder if `*.chs.c` files could also be generated with the implementations of `wrap_*` functions.

I'm not sure what the syntax for such as feature would look like—perhaps something like this:

```c
{#fun pure wrap coord_x as coordX { `CoordPtr' } -> `Int' #}

data Coord
{#pointer *coord_t as CoordPtr -> Coord #}
```

that could automatically generate this Haskell FFI code:

```
foreign import ccall safe "<module>.chs.h wrap_coord_x"
  coordX'_ :: CoordPtr -> CInt
```

where `wrap_coord_x` is defined in `<module>.chs.h` and implemented in `<module>.chs.c`? There'd probably need to be further name-mangling in case there's already a `wrap_coord_x` defined as well.

**Comment by ian-ross** [comment]
This should be doable.  I've put it on the list for release 0.24.1 (0.22.1 is today, 0.23.1 is probably in the next couple of weeks, so 0.24.1 should be in a month or so).

**Comment by aloiscochard** [comment]
Would be great to see this feature added! :+1: ty

**Comment by ian-ross** [comment]
@aloiscochard It's actually the very next thing on my to-do list for today...

**Comment by ian-ross** [comment]
@RyanGlScott @aloiscochard OK, it's taken me most of the day, but I think I have this working now.  If you have this C code in a header file:

```c
typedef struct {
  int x;
  int y;
} coord_t;

coord_t *make_coord(int x, int y);
void free_coord(coord_t *coord);
int coord_x(coord_t c);
```

and you have this C2HS code:

```c2hs
#include "header.h"

{#pointer *coord_t as CoordPtr foreign finalizer free_coord newtype#}

{#fun pure make_coord as makeCoord {`Int', `Int'} -> `CoordPtr'#}
{#fun pure coord_x as coordX {%`CoordPtr'} -> `Int'#}

main :: IO ()
main = do
  let c = makeCoord 5 6
  let x = coordX c
  print x
```

(note the `%` in the definition of the `coordX` function -- this is what triggers wrapper generation) then when you run C2HS on this, you'll get the usual Haskell code generated, but also a `blah.chs.c` file containing wrapper functions converting from Haskell FFI pointer passing to bare structure parameters.

You then need to compile those C wrappers and link the resulting object with your Haskell code.  I don't know how that will work with Cabal -- you'll probably need to write a custom build script to handle it, but it ought to be possible.

Anyway, this is only slightly tested and is kind of complicated, so it wouldn't surprise me if you could break it quite easily.  Give it a go and let me know how you get on!

**Comment by RyanGlScott** [comment]
That is incredibly neat! As you noted, the biggest challenge in using this is telling `cabal` where the generated `*.chs.c` files are. After failing to build the example once, I discovered where `Main.chs.c` was, so I manually added this to my project's `.cabal` file:

```
includes:            foo.h
include-dirs:        cbits
c-sources:           cbits/foo.c
                   , dist/dist-sandbox-7253b662/build/c2hs-test/c2hs-test-tmp/Main.chs.c
```

It works, but it's pretty ugly, and this particular directory structure only works for sandboxes, so it's not general enough.

I wonder though: how does `cabal` know where to look for `Main.chs.h`, even though it isn't explicitly added to the `includes` field? Perhaps understanding that could help uncover a better way of doing this.

**Comment by ian-ross** [comment]
@RyanGlScott Well, C2HS is a know preprocessor in Cabal, so there's support built into Cabal for managing setting up the include path to the `chs.h` files.  I guess we'd need to add support for compiling the `chs.c` files as well (or perhaps just for moving the `chs.c` to a well-know location).  I'm not sure what the best way to do it is.  I'll have a look and see if I can work it out and if not I'll ask Duncan or Andres.

**Comment by ian-ross** [comment]
@RyanGlScott A quick investigation reveals that this might be "tricky".  There's an outstanding C2HS ticket to support the same sort of thing for hsc2hs (https://github.com/haskell/cabal/issues/238), but it looks like it would require some medium-sized changes to the way that Cabal deals with preprocessors to make it work.  I'll see if I can hack something together this week, but don't get your hopes up.

**Comment by aloiscochard** [comment]
that is great thanks @ian-ross !

I'll try the feature now, even with the known limitation I think it's a big win.

**Comment by aloiscochard** [comment]
I got this error:
`c2hs: src/C2HS/Gen/Wrapper.hs:(66,1)-(67,32): Non-exhaustive patterns in function fixArgs`

When trying to add a custom "in" marshaller to a field that had the `%` annotation.

**Comment by aloiscochard** [comment]
Actually the error message happen because I had a mismatch between my types:

`{#fun grpc_completion_queue_next as ^ {`CompletionQueue', id `CTimeSpec'} -> `CompletionQueue'#}`

instead of:
`{#fun grpc_completion_queue_next as ^ {`CompletionQueue', id `CTimeSpec'} -> `Event'#}`

When the def is:
```
grpc_event *grpc_completion_queue_next(grpc_completion_queue *cq,
                                       gpr_timespec deadline);
```

**Comment by ian-ross** [comment]
Hi @aloiscochard -- very happy to see that you're already playing with this!  I was hoping that you and @RyanGlScott would do your best to break it: it's very much an experimental feature and there are definitely going to be some problems with it.

One thing that would be really useful is if you could pull the latest version that I've just committed and do whatever you did that gave you the non-exhaustive pattern message again.  I've added some debugging output to help with the (rather horrible) partial pattern matches to C AST fragments in the code that makes the C wrapper functions.  If you can send me the (very messy but honestly useful) debug output, that would be great.  (If you can also let me know what the C2HS code it was processing looks like and any associated C definitions, that would make life easier.)

It's probably a good thing that this isn't yet accessible via Cabal, since it's not quite ready for general use.  As for the Cabal stuff, I know what to do, but it's just a matter of clearing a day or half a day to do it.  I'm hoping to I'll be able to submit a PR for Cabal in the next week or two.

**Comment by aloiscochard** [comment]
Hi @ian-ross -- I just started using c2hs for the first time, also my C is very rusty and it's the first time I'm writing a C binding for haskell.

Just to warn you that I might just do it wrong!

Here is the code (the lib is https://github.com/grpc/grpc/tree/master/include/grpc):
https://github.com/aloiscochard/grpc-haskell/blob/0f5042bf2e5a45ad09dfc61bc412e6157990a7de/src/Network/GRPC.chs#L37

The output:

```
c2hs: NON-EXHAUSTIVE PATTERN IN fixArgs
args=[False,True]
cdecl=CDeclr (Just (Ident "__c2hs_wrapped__grpc_completion_queue_next" 262654987 (OnlyPos <internal> (<no file>,-1)))) [CFunDeclr (Right ([CDecl [CTypeSpec (CTypeDef (Ident "grpc_completion_queue" 327603445 (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),21) (Name {nameId = 7495}))) (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),21) (Name {nameId = 7496})))] [(Just (CDeclr (Just (Ident "cq" 14563 (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),2) (Name {nameId = 7497})))) [CPtrDeclr [] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),2) (Name {nameId = 7499}))] Nothing [] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),2) (Name {nameId = 7498}))),Nothing,Nothing)] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),2) (Name {nameId = 7500})),CDecl [CTypeSpec (CTypeDef (Ident "gpr_timespec" 355575246 (NodeInfo ("/usr/include/grpc/grpc.h": line 381) (("/usr/include/grpc/grpc.h": line 381),12) (Name {nameId = 7501}))) (NodeInfo ("/usr/include/grpc/grpc.h": line 381) (("/usr/include/grpc/grpc.h": line 381),12) (Name {nameId = 7503})))] [(Just (CDeclr (Just (Ident "deadline" 424945616 (NodeInfo ("/usr/include/grpc/grpc.h": line 381) (("/usr/include/grpc/grpc.h": line 381),8) (Name {nameId = 7502})))) [] Nothing [] (NodeInfo ("/usr/include/grpc/grpc.h": line 381) (("/usr/include/grpc/grpc.h": line 381),8) (Name {nameId = 7504}))),Nothing,Nothing)] (NodeInfo ("/usr/include/grpc/grpc.h": line 381) (("/usr/include/grpc/grpc.h": line 381),8) (Name {nameId = 7505}))],False)) [] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 381),1) (Name {nameId = 7506})),CPtrDeclr [] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 381),1) (Name {nameId = 7507}))] Nothing [] (NodeInfo ("/usr/include/grpc/grpc.h": line 380) (("/usr/include/grpc/grpc.h": line 380),26) (Name {nameId = 7494}))
```

Thanks for being so reactive and doing your best to get this feature integrated with Cabal!

Cheers

**Comment by ian-ross** [comment]
@aloiscochard Thanks -- that's great, and should give me enough information to improve this (I won't say "fix this" because it might take a few iterations to make it work perfectly, but I can certainly make it better!).  I'll take a look at it tomorrow evening.

**Comment by RyanGlScott** [comment]
Since this will require some modifications to `Cabal` to make it work, it might be worthwhile to have a `Setup.hs` script that can detect where the `.chs.c` files are with older versions of `Cabal`. I tried looking into this recently, and to my dismay, `Cabal` doesn't seem to provide a hook that executes in between the build step (when the `.chs.c` files are created) and GHC's linker step (when you need to tell `Cabal` where the `.chs.c` are located).

As a super-hacky workaround, I devised a `Setup.hs` script in which before `cabal build` is run, adding any `.chs.c` files it can find to the `c-sources` field, and if it fails (which is guaranteed when you run it the first time, since the `.chs.c` files are created sometime in the middle of `cabal build`), it tries again. As a result, this could spit out some linker errors initally, but everything should resolve itself subsequently:

```haskell
module Main (main) where

import Control.Exception (catch)
import Control.Monad (forM)

import Distribution.PackageDescription
    (BuildInfo(..), Executable(..), Library(..), PackageDescription(..))
import Distribution.Simple (UserHooks(..), defaultMainWithHooks, simpleUserHooks)
import Distribution.Simple.LocalBuildInfo (LocalBuildInfo(..))
import Distribution.Simple.Setup (BuildFlags)
-- Test-suites require Cabal-1.10 or greater
import Distribution.PackageDescription (TestSuite(..))
-- Benchmarks require Cabal-1.14 or greater
import Distribution.PackageDescription (Benchmark(..))

import System.Directory (doesDirectoryExist, getDirectoryContents)
import System.Exit (ExitCode)
import System.FilePath ((</>), takeExtensions)

main :: IO ()
main = defaultMainWithHooks simpleUserHooks { buildHook = chsBuildHook }

addCSources :: [FilePath] -> BuildInfo -> BuildInfo
addCSources newSrcs bi@(BuildInfo { cSources = oldSrcs }) = bi { cSources = newSrcs ++ oldSrcs }

hasChsCExtension :: FilePath -> Bool
hasChsCExtension file = takeExtensions file == ".chs.c"

getRecursiveContents :: FilePath -> IO [FilePath]
getRecursiveContents topdir = do
    topdirExists <- doesDirectoryExist topdir
    if (not topdirExists)
       then return []
       else do
           names <- getDirectoryContents topdir
           let properNames = filter (`notElem` [".", ".."]) names
           paths <- forM properNames $ \name -> do
               let path = topdir </> name
               isDirectory <- doesDirectoryExist path
               if isDirectory
                  then getRecursiveContents path
                  else return [path]
           return (concat paths)

chsBuildHook :: PackageDescription -> LocalBuildInfo -> UserHooks -> BuildFlags -> IO ()
chsBuildHook pd lbi uh bf = hook `catchExitCode` \_ -> hook
  where
    hook :: IO ()
    hook = chsBuildHook' pd lbi uh bf
    
    catchExitCode :: IO a -> (ExitCode -> IO a) -> IO a
    catchExitCode = catch

chsBuildHook' :: PackageDescription -> LocalBuildInfo -> UserHooks -> BuildFlags -> IO ()
chsBuildHook' pd@(PackageDescription
                   { library     = mbLib
                   , executables = exes
                   , testSuites  = tss
                   , benchmarks  = bms
                   })
             lbi uh bf = do
    let distBuildDir = buildDir lbi
    chsCFiles <- fmap (filter hasChsCExtension) $ getRecursiveContents distBuildDir
    let pd' = pd { library     = fmap (\lib -> lib { libBuildInfo       = addCSources chsCFiles (libBuildInfo lib)      }) mbLib
                 , executables = fmap (\exe -> exe { buildInfo          = addCSources chsCFiles (buildInfo exe)         }) exes
                 , testSuites  = fmap (\ts  -> ts  { testBuildInfo      = addCSources chsCFiles (testBuildInfo ts)      }) tss
                 , benchmarks  = fmap (\bm  -> bm  { benchmarkBuildInfo = addCSources chsCFiles (benchmarkBuildInfo bm) }) bms
                 }
    buildHook simpleUserHooks pd' lbi uh bf
```

Note that this assumes that `.chs.c` files are all placed in the `/dist/.../build` directory.

**Comment by ian-ross** [comment]
@RyanGlScott  Yay!  You're a hero!  And yes, it is wacky, but I was thinking about doing something similar for old versions of Cabal.  And now I don't have to.  I'll try to get the Cabal changes done over the weekend and have a branch of cabal-install you can try.  I don't think it will be all that hard to do.

I'm going to reopen this, since it's not really solved until we have a seamless solution with Cabal.

**Comment by ian-ross** [comment]
@aloiscochard I've made some changes that should deal with that particular problem (basically when you try to make a wrapper for an argument that's already a pointer).  You should now get a useful error message when that happens.

See if you can break it some other way now!  I'm going to try to do the Cabal preprocessor stuff tomorrow.

**Comment by ian-ross** [comment]
@RyanGlScott @aloiscochard  I've made some changes to Cabal to deal with these extra C sources produced from C2HS.  If you clone my Cabal repo (https://github.com/ian-ross/cabal), switch to the `preprocessor-extra-sources` and follow the instructions in `HACKING.md` file to get things built, you should hopefully be able to build packages that use these C2HS wrappers via Cabal.  Have a play with it and if it works, I'll raise a PR for Cabal.

**Comment by ian-ross** [comment]
I'm going to close this now -- there's a PR in to Cabal to support processing of the extra C source (https://github.com/haskell/cabal/pull/2467), so I think this is pretty much done.

**Comment by ian-ross** [comment]
The PR to Cabal is unlikely to be accepted because it will break all the Gtk packages.  Given the current design of the Cabal API, it's hard to see how to make any changes to the way that preprocessors are handled without breaking loads of things.  Giving up for now.

**Comment by deech** [comment]
Sorry to re-open this issue but I have a lot of functions that return a stack allocated struct, something like:
```
coord_t make_coord(int x, int y) { ...
```
Is there any way to use the `%` syntax to marshal a bare struct when it is returned?
