### ISSUE TITLE
Lexical error on #line pragma

### ISSUE THREAD

**Issue by phaazon** [haskell/c2hs#119]
Hi,

I tried to install `cuda`, and I got [that issue from `c2hs`](http://lpaste.net/119875). I have no idea how to fix that :(

**Comment by ian-ross** [comment]
@phaazon Could you tell me what version of C2HS you have installed?  I made some changes related to `#line` pragmas a little while ago, so I just want to be sure that this problem is still there in the current version of C2HS.

**Comment by phaazon** [comment]
Sure:

```
phaazon@illusion ~
$ c2hs --version
C->Haskell Compiler, version 0.22.1 Snowbounder, 31 Oct 2014
  build platform is "x86_64-mingw32" <1, True, True, 1>
```

**Comment by ian-ross** [comment]
Can you go to the `Foreign/CUDA` directory within the `cuda` package and run the following, replacing `/opt/cuda/include` with the path to the `include` directory in your CUDA installation:

```
c2hs -C -I../.. -C -I/opt/cuda/include -k -d trace Types.chs
```

(I guess you'll have to say `c2hs.exe` if you're on Windows.)

I'm guessing that this is something to do with differences between the C preprocessor under Linux and MinGW on Windows.  I don't have a Windows system set up for testing, but I'll see if I can figure out what's going on from the output of the above command.

**Comment by phaazon** [comment]
```
phaazon@ILLUSION ~/dev/cuda/Foreign/CUDA (fix_#15)
$ c2hs -C -I../.. -C -I/c/NVIDIA/CUDAToolkit/include/ -k -d trace Types.chs
Attempting to read file `Types.chs'...
...parsing `Types'...
...successfully loaded `Types'.
Invoking cpp as `cpp -x c -I../.. -Ic:/NVIDIA/CUDAToolkit/include/ -U__BLOCKS__ -DC2HS_VERSION_MAJOR=0 -DC2HS_VERSION_MI
NOR=22 -DC2HS_VERSION_REV=1 Types.chs.h'...
In file included from c:/NVIDIA/CUDAToolkit/include/cuda_runtime_api.h:142:0,
                 from ../../cbits/stubs.h:26,
                 from Types.chs.h:2:
c:/NVIDIA/CUDAToolkit/include/host_defines.h:79:0: warning: "__cdecl" redefined [enabled by default]
 #define __cdecl
 ^
Types.chs.h:1:0: note: this is the location of the previous definition
 #define C2HS_MIN_VERSION(mj,mn,rv) ((mj)<=C2HS_VERSION_MAJOR && (mn)<=C2HS_VERSION_MINOR && (rv)<=C2HS_VERSION_REV)
 ^
Attempting to read file `Types.i'...
...parsing `Types.i'...
...name analysis of `Types.i'...
...successfully loaded `Types.i'.
...expanding binding hooks...
...successfully completed.
```

**Comment by phaazon** [comment]
I read in the `cuda` package that `c2hs` got passed the NVIDIA compiler, which basically simply adds a preprocessor. Running your command with it generates the following error:

```
phaazon@ILLUSION ~/dev/cuda/Foreign/CUDA (fix_#15)
$ c2hs -C -I../.. -C -I/c/NVIDIA/CUDAToolkit/include/ -k -d trace Types.chs --cpp=nvcc
Attempting to read file `Types.chs'...
...parsing `Types'...
...successfully loaded `Types'.
Invoking cpp as `nvcc -x c -I../.. -Ic:/NVIDIA/CUDAToolkit/include/ -U__BLOCKS__ -DC2HS_VERSION_MAJOR=0 -DC2HS_VERSION_M
INOR=22 -DC2HS_VERSION_REV=1 Types.chs.h'...
c2hs.exe: Error during preprocessing custom header file
```

**Comment by ian-ross** [comment]
Let me have a proper look (probably on Friday or Saturday).  We fixed one problem with using nvcc via c2hs recently, but I think that was something a bit different.

**Comment by ian-ross** [comment]
I've written a long comment about this problem here: https://github.com/tmcdonell/cuda/issues/25 -- unfortunately, I don't think this particular problem is going to be fixed, since it's likely to involve having to  try to get C2HS to work with the Microsoft C compiler, which is not something I want to spend time on.  On that basis, I'm going to close this issue.  I'd suggest that any further discussion be done under that `cuda` package issue.
