### ISSUE TITLE
Not in scope: type constructor or class 'CBool'

### ISSUE THREAD

**Issue by cocreature** [haskell/c2hs#127]
I have a function that returns a Bool. c2hs turns
`
{#fun wlc_init as ^ { with* `WLCInterface', withArrayLen `[String]' } -> `Bool' #}`
(ignore the withArrayLen, I still need to figure the rest out) into
`
foreign import ccall safe "WLC.chs.h wlc_init"
  wlcInit'_ :: ((WLCInterfacePtr) -> (CInt -> (IO CBool)))
`
However CBool does not exist in Foreign.C.Types. I couldn't find it via Hayoo or Hoogle either.

**Comment by ian-ross** [comment]
Dammit.  Sorry about that.  I just introduced that today to fix another issue.  I'll fix this tomorrow.

**Comment by cocreature** [comment]
Alright, thanks.
