### ISSUE TITLE
Void field in struct

### ISSUE THREAD

**Issue by handerpeder** [haskell/c2hs#133]
I'm trying to compile [Enet](http://enet.bespin.org/) bindings from [HGamer3D](https://github.com/urs-of-the-backwoods/HGamer3D); a game engine of sorts in Haskell.

With 0.25.2 I get the following error

```
c2hs: Errors during expansion of binding hooks:

include/ClassPtr.h:47: (column 1) [ERROR]  >>> Void field in struct!
  Attempt to access a structure field of type void.
include/ClassPtr.h:44: (column 1) [ERROR]  >>> Void field in struct!
  Attempt to access a structure field of type void.
include/ClassPtr.h:41: (column 1) [ERROR]  >>> Void field in struct!
  Attempt to access a structure field of type void.
include/ClassPtr.h:38: (column 1) [ERROR]  >>> Void field in struct!
  Attempt to access a structure field of type void.
```

The header in question is located [here](https://github.com/urs-of-the-backwoods/HGamer3D/blob/master/Bindings/Enet/hBuild/include/ClassPtr.h).

I'm able to compile using c2hs-0.20.1 from cabal.

Is this a regression?

**Comment by ian-ross** [comment]
That does indeed look like a regression, and I can imagine what changes caused it.  I'll take a look at it over the weekend.

**Comment by ian-ross** [comment]
@handerpeder  Can you show me the C2HS code you're using?  I've experimented a little and I've not been able to reproduce this with what I could guess you might be doing.

**Comment by handerpeder** [comment]
Sure.

I'm trying to compile HGamer3D (not a project I have contributed to).

The chs file is [here](https://github.com/urs-of-the-backwoods/HGamer3D/blob/master/Bindings/Enet/hBuild/HGamer3D/Bindings/Enet/ClassPtr.chs)

I'm basically just calling cabal (through scons) in the `HGamer3D/Bindings/Enet/hBuild` folder.after installing the dependencies (from Deps folder) and compiling the native part (from cBuild folder).

Hope this helps.

**Comment by ian-ross** [comment]
@handerpeder  OK, not completely sure why this stopped working, but it should be OK in HEAD now.  It was just the special case of having a `typedef void c_something` and a {#pointer *c_something as Something#}`.  I'd never seen `typedef void ...` before -- didn't even know it was legal C!
