### ISSUE TITLE
Can't use CPP pragmas in enum define declarations

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/c2hs#135]
I'm currently experiencing an architectural issue in a project I'm working on that involves BlueZ and `c2hs`. I'm using the `enum define` feature to create a [rather large data type](https://github.com/RyanGlScott/bluetooth/blob/68637f5bb1c614a03fa32baf5e9e6c7d96c8335f/src/Network/Bluetooth/Linux/UUID.chs#L38-107); it looks something like this:

```haskell
{#enum define UUIDServiceClass
  { SDP_SERVER_SVCLASS_ID  as ServiceDiscoveryServer
  ...
  , APPLE_AGENT_SVCLASS_ID as AppleAgentService
  } #}
```

The problem is that a particular macro constant (`GENERIC_ACCESS_SVCLASS_ID`) [has only been around since BlueZ 5.14](http://git.kernel.org/cgit/bluetooth/bluez.git/commit/lib/sdp.h?id=a0d40b384aa11e9a57d37a5428e2da07fad8bdd6), so I need to use CPP to ensure that machines with old versions of BlueZ don't try accessing `GENERIC_ACCESS_SVCLASS_ID`. Here is how I would attempt to do so:

```haskell
{-# LANGUAGE CPP #-}

{#enum define UUIDServiceClass
  { SDP_SERVER_SVCLASS_ID     as ServiceDiscoveryServer
#if defined(BLUEZ_VERSION) && BLUEZ_VERSION >= 514
  , GENERIC_ACCESS_SVCLASS_ID as GenericAccess
#endif
  , APPLE_AGENT_SVCLASS_ID    as AppleAgentService
  } #}
```

Unfortunately, `c2hs` runs before the CPP preprocessor, resulting in this error:

```
src/Main.chs:11: (column 2) [ERROR]  >>> Syntax error!
  The phrase `if' is not allowed here.
src/Main.chs:13: (column 1) [ERROR]  >>> Lexical error!
  The character '#' does not fit here; skipping it.
src/Main.chs:11: (column 45) [ERROR]  >>> Lexical error!
  The character '>' does not fit here; skipping it.
src/Main.chs:11: (column 1) [ERROR]  >>> Lexical error!
  The character '#' does not fit here; skipping it.
```

So at the moment, I can't conditionally define enum constructors without surrounding the entire `enum define` declaration in CPP pragmas, which would get quite ugly. Is there a way to hack `c2hs` so that something like what I'm envisioning can be achieved?

**Comment by ian-ross** [comment]
Urgh.  My immediate off-the-top-of-my-head answer is "No", but let me think about it.  The interaction between C2HS and C preprocessing is kind of nasty, so this might be hard to do in any reasonable way.

**Comment by mikesteele81** [comment]
@RyanGlScott How about conditionally defining that constant in a `#c`/`#endc` block before the `#enum define` call hook?

**Comment by RyanGlScott** [comment]
I could do that, but it would lead to different runtime behavior when broadcasting UUID protocols on different versions of BlueZ (since BlueZ [maps certain macro constants to human-readable names](http://git.kernel.org/cgit/bluetooth/bluez.git/tree/lib/sdp.c?id=5f12d7a3da6869bb25154d594c5d9503b33cbe6c#n113)).

I could forgo `enum define` and define an `Enum` instance manually, but automating it with build tools is pretty nice. I understand that this is wading into the "probably not possible" side of things, but I'd figure that I should ask just in case.

**Comment by mikesteele81** [comment]
@RyanGlScott 

It sounds like you are trying to generate different Haskell interfaces based on the C library's version. My suggestion was the opposite of that (generate the same Haskell interface by papering over differences in the C header files). I thought I'd mention it just in case it would be helpful.

**Comment by RyanGlScott** [comment]
That's definitely good advice. I hadn't considered how messy that would make the Haskell API, and it would probably be more informative to catch problems like these from Haskell code, where I could freely use CPP as I wish.

In that case, it's probably not worth pursuing this bug, especially since it sounds like it would take a substantial reengineering effort to implement.

**Comment by ian-ross** [comment]
@RyanGlScott  Thanks for closing this one!  I think it would be bad news to try to make this work...
