### ISSUE TITLE
incorrect sizeof for structs with padding at the end

### ISSUE THREAD

**Issue by eboasson** [haskell/c2hs#156]
It appears the padding of a struct to make its size a multiple of its alignment doesn't happen. This also means embedding a struct for which this happens in another struct causes any subsequent fields to have incorrect offsets. Attached is a simple case that triggers it.

A minor change makes this case (and my actual problem go away):
```
diff --git a/src/C2HS/Gen/Bind.hs b/src/C2HS/Gen/Bind.hs
index 03b5f53..e176d06 100644
--- a/src/C2HS/Gen/Bind.hs
+++ b/src/C2HS/Gen/Bind.hs
@@ -2420,7 +2420,7 @@ sizeAlignOfStructPad decls tag =
   do
     (sz, align) <- sizeAlignOfStruct decls tag
     let b = size CIntPT
-    return (alignOffset sz b b, align)
+    return (alignOffset sz align b, align)
 
 -- | compute the size and alignment constraint of a given C declaration
 --
```

[bug.zip](https://github.com/haskell/c2hs/files/111183/bug.zip)

**Comment by takano-akio** [comment]
I also encountered the same problem, and @eboasson's patch above fixed the issue.

**Comment by ian-ross** [comment]
@eboasson Thanks for the report.  I'll try to look at this this weekend.

**Comment by ian-ross** [comment]
Thanks for this: the fix turned out to involve a tiny bit more (mostly to do with sizing for bitfields), but I've added a test case to make sure this doesn't break again.
