### ISSUE TITLE
Support language-c 0.7

### ISSUE THREAD

**Issue by albertov** [haskell/c2hs#194]
So it includes the fix for https://github.com/visq/language-c/issues/34 which is causing the build of [bindings-gdal](https://github.com/albertov/bindings-gdal) to fail on OS X

**Comment by albertov** [comment]
Adjusting the version bounds in `.cabal` fails with: 
```
src/C2HS/CHS/Lexer.hs:715:34: error:
    Variable not in scope:
      adjustPos :: String -> t0 -> Position -> Position
```

**Comment by deech** [comment]
I have a fix for this on my branch https://github.com/deech/c2hs/commit/8b79823c32e234c161baec67fdf7907952ca62b8. I was also working on the `__float128` vs `_Float128` bug but if you really need `language-c 0.7` I can cut another release.

**Comment by albertov** [comment]
No hurries. I can pull `c2hs` directly from your branch for `bindings-gdal`'s CI easily to see how it goes and update it when you're ready for a release.
Thanks!

**Comment by deech** [comment]
That `_Float128` test isn't passing. If you don't care about that go ahead and pull otherwise I'll fix it later this morning.

**Comment by albertov** [comment]
I can confirm that your branch allows building `bindings-gdal` on OSX X!

The failing doesn't bother me at all, I'm building with nix so `dontCheck` "solves" the issue for the meantime.

**Comment by albertov** [comment]
I've just seen that this is a duplicate of #193.
