### ISSUE TITLE
Map the `size_t' C type to Foreign.C.CSize

### ISSUE THREAD

**Issue by ian-ross** [haskell/c2hs#20]
Bug imported from [C2HS Trac](http://hackage.haskell.org/trac/c2hs/ticket/20)

Trac ticket created: 2009-07-04T21:27:02-0700; last modified: 2009-09-30T21:18:58-0700

----

Currently, size_t is mapped to either CUInt or CULong, depending on the native integer size. This means that type signatures will not be portable between 32- and 64-bit installations.

**Comment by ian-ross** [comment]
@Rufflewind I believe the HEAD version of C2HS now has the capability to do this.  I implemented a rather general mechanism for associating C typedefs with given Haskell types (and assigning default marshallers for them, although that's not needed here).  Take a look at the test case for this issue in the repo to see how to do it.

**Comment by Rufflewind** [comment]
Thanks!

**Comment by ian-ross** [comment]
@Rufflewind  Let me know if you think the mechanism I implemented (the new `typedef` and `default` hooks) is any good.  I think it covers most of the cases I could imagine people wanting to do.

**Comment by Rufflewind** [comment]
I think the new mechanism will work well (I couldn't think of any exceptions).  It enables the separation between the type alias that forms the API and the underlying type that may be platform-dependent.
