### ISSUE TITLE
No marshaller for CULLong and C2HSImp.CULLong

### ISSUE THREAD

**Issue by vmchale** [haskell/c2hs#242]
This seems to be an oversight; I can work around it by using `id` to marshal in/out. 

See e.g. https://github.com/vmchale/lzlib/blob/master/src/Codec/Lzip/Raw.chs#L86. 

If I remove the `id` marshalers I get

```
c2hs: Errors during expansion of binding hooks:

src/Codec/Lzip/Raw.chs:83: (column 48) [ERROR]  >>> Missing "in" marshaller!
  There is no default marshaller for this combination of Haskell and C type:
  Haskell type: CULLong
  C type      : C2HSImp.CULLong
```

**Comment by deech** [comment]
Fixed https://github.com/haskell/c2hs/pull/243. Please close if it works for you.

**Comment by vmchale** [comment]
Thanks :)
