### ISSUE TITLE
tests fail against shelly-1.9: No instance for (CmdArg Char) arising from a use of ‘cmd’

### ISSUE THREAD

**Issue by trofi** [haskell/c2hs#245]
Noticed test build failure after `shelly-1.9` update:
```
$ runhaskell Setup.hs configure --enable-tests && runhaskell Setup.hs build
```

```
tests/test-bugs.hs:466:44: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: Text
        Actual type: FilePath
    • In the expression: lcc <.> "o"
      In the second argument of ‘cmdAll’, namely
        ‘["-c", "-o", lcc <.> "o", lc <.> "c"]’
      In the second argument of ‘($)’, namely
        ‘cmdAll cc ["-c", "-o", lcc <.> "o", lc <.> "c"]’
    |
466 |       when cbuild $ cmdAll cc ["-c", "-o", lcc <.> "o", lc <.> "c"]
    |                                            ^^^^^^^^^^^
```

Looks like it's caused by removal of `instance CmdArg FilePath where toTextArg = toTextIgnore` : https://github.com/gregwebs/Shelly.hs/commit/8288d27b93b57574135014d0888cf33f325f7c80#diff-bb53513ad3d8403c781068f6d4466dceL186

**Comment by nganhkhoa** [comment]
It seems that we need to change from String to Text. A naive solution is `T.pack` everywhere. Any other suggestions?

This issue stop testing, and build status is always `failing`.

**Comment by andreasabel** [comment]
@deech: This issue is fixed, AFAICT, and can be closed.

**Comment by deech** [comment]
Thanks!
