### ISSUE TITLE
cannot parse: __uint128_t

### ISSUE THREAD

**Issue by agentultra** [haskell/c2hs#296]
This might be a `language-c` issue or a pebkac, but when I try to parse a header file with a sensible typedef of:

```
typedef __uint128_t tb_uint128_t;
```

I tried to write,

```
{#typedef tb_uint128_t Word128#}
```

And run `c2hs` on my `.chs` file, I get:

```
[ERROR]  >>> Illegal type!
  The type specifiers of this declaration do not form a legal ANSI C(89) type.
```

Am I doing something wrong with the specification here or is this a bug? Happy to help contribute a fix if I am able.

**Comment by Bodigrim** [comment]
Where does `Word128#` come from? `base` defines `Word32#` and `Word64#`, but not `Word128#`.

**Comment by agentultra** [comment]
It comes from the ‘wideword’ package. Defined as a record with a hi and lo Word64 fields. It's sounding more like I need to write another C library over top to pass pointers.

This header I'm trying to write FFI for uses `__uint128_t` passing by value and there are several structs with them as fields.

I thought maybe there was a way for c2hs to generate the bindings to marshal these. But if I can't even parse the definition maybe my wrapper library will have to define it's own typedef :thinking:

**Comment by agentultra** [comment]
Ok, so `__uint128_t` is defined by GCC and is a non-standard type. I can see why it wouldn't make sense for `c2hs` to support this. There is a workaround for this. Thanks for taking a peek at this issue!
